import { useEffect, useState } from 'react'
import Head from 'next/head'
import { Layout } from '@/components/Layout'
import { CharacterList } from '@/components/CharacteresList'
import { getCharactersData } from 'services/CharacterService'
import { api } from 'lib/api'
import { CharacterListProps } from '@/components/CharacteresList/characterList.types'
import { Search } from '@/components/Search'
const mock = [{
  name: 'Rick',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg'
},
{
  name: 'Pedro',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg'
},
{
  name: 'Seu Jorge',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg'
},
{
  name: 'Gleyce',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg'
},
{
  name: 'Estevão ferreira',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg'
}
,
{
  name: 'Estevão ferreira',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg'
}
,
{
  name: 'Estevão ferreira',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg'
}
,
{
  name: 'Estevão ferreira',
  status: 'ativo',
  image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg'
}]

export default function Home() {
  const [characters, setCharacters] = useState<CharacterListProps | null >(null);

  const getAllCharacters = async (params: string) => {
    const res:CharacterListProps = await getCharactersData(params)
    console.log(res)
    setCharacters(res)
  }

   useEffect( () =>   {
    console.log('render')
    getAllCharacters('')
  }, [api])
  return (
    <>
      <Head>
        <title>Página inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap" rel="stylesheet" />
      </Head>
      <Layout>
        <Search setCharacters={setCharacters}/>
        <CharacterList
        results={characters && characters.results}/>
      </Layout>
    </>
  )
}
