import Head from 'next/head'
import { Layout } from '@/components/Layout'
//import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Página inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap" rel="stylesheet" />
      </Head>
      <Layout>
        
      </Layout>
    </>
  )
}
